### PR TITLE
Fixed bad version on for the cotiviti-license-lib

### PR DESCRIPTION
**Pull request by isomarcte**
* `cotiviti-nexgen-parent/cotiviti-scala-parent/pom.xml`
  * `${project.version}` won't work here because it resolves to the
    target POM, i.e. the project in which the license plugin is being
    run. We have to hard code it. This is *okay* because it *should*
    fail the release because of the SNAPSHOT version, forcing someone to
    update it, but it is unfortunate.

### CODE REVIEW

**Comment by isomarcte** [comment]
@apoland please review/merge

**Comment by apoland** [comment]
Hmm we may need to break cotiviti-license-lib out into it's own repo so it can be released independently of cotiviti-parent.  @mykelalvis does that make sense to you?

**Comment by isomarcte** [comment]
That's not a bad idea. I should be pretty static. I'll make the changes tomorrow.

**Comment by apoland** [comment]
@isomarcte Cool.  I talked to Mykel and yeah it has to be released separately for this to work.  Looks like breaking it into its own project is the only way to solve the problem.

**Comment by isomarcte** [comment]
Okay this now uses the new `cotiviti-license-libs` repo and fixes the issue where `license:format` was not being run in the `process-sources` phase.

@apoland, @mykelalvis requested to review this PR before merge so I am changing assignment to him.

**Comment by mykelalvis** [comment]
So having it as a separate module is fine.  It's entirely possible that this is the moment where we start thinking about  splitting `cotiviti-parent` away and make a `labs-parent` as the top of this tree that depends on `cotiviti-parent` which would have essentially no config in it at all.

**Comment by mykelalvis** [comment]
I’m willing to accept this PR with the knowledge that it probably opens a can of worms that was gonna need to be open anyway...

We can have that talk here or we can make it a totally separate issue.  Thoughts anyone?

**Comment by isomarcte** [comment]
@mykelalvis what is the can of worms?

**Pull request merged**
