### PR TITLE
Added more strict warnings and runtime checks to scalac.

### PR DESCRIPTION
**Pull request by isomarcte**
* Added more static code warning checks to scalac.
* Made warnings fatal.
* Added additional runtime safety checks provided by scalac.
* Added more verbose type explanations.
* Enabled all warnings when `scala-maven-plugin` is used to compile java
  code. Also treats warnings as errors.

### CODE REVIEW

**Comment by isomarcte** [comment]
@gyounge1 can you add this as a discussion topic to the all hands on Monday as well. Thanks.

**Comment by sunnylbk** [comment]
@isomarcte This has conflicts with the original file.

**Comment by isomarcte** [comment]
One sec. Let me rebase.

**Comment by isomarcte** [comment]
Should be good now.

**Pull request merged**
